### PR TITLE
Fix: Grid columns dont have width set correctly

### LINKED ISSUE #863: 1.7 Grid Block, the initial grid columns have no widths
### Description
When adding a new Grid and selecting an option from the Select Layout panel, the grid items get loaded without any widths:

https://user-images.githubusercontent.com/30641942/212466869-80a25c23-8a94-4662-bddb-b1fdcf8de959.mov

### PR DESCRIPTION
**Pull request by JeanPaiva**
Closes #863

### CODE REVIEW

File: src/blocks/grid/components/LayoutSelector.js [hunk 1]
```diff
@@ -28,6 +28,9 @@ export const getColumnsFromLayout = ( layout, uniqueId ) => {
 		paddingLeft: gridItemPaddingLeft || '',
 		widthMobile: 100,
 		width: Number( col ),
```
Comment (tomusborne) [inline src/blocks/grid/components/LayoutSelector.js:30]: I think we can remove this.

Comment (JeanPaiva) [reply src/blocks/grid/components/LayoutSelector.js]: @tomusborne done, removed the width.

**Review by tomusborne — APPROVED** [review]
