### PR TITLE
Fix: Color and Background panels are visible/accessible on Responsive views

### LINKED ISSUE #953: Color and Background panels are visible/accessible on Responsive views
### Description
Inspector controls for panels such as Colors and Backgrounds are visible in responsive controls when they are not responsive

### PR DESCRIPTION
**Pull request by JeanPaiva**
Closes #953

### CODE REVIEW

File: src/extend/inspector-control/index.js [hunk 1]
```diff
@@ -68,14 +68,14 @@ export default function GenerateBlocksInspectorControls( { attributes, setAttrib
 				/>
 			}
 
-			{ colors.enabled &&
+			{ colors.enabled && 'desktop' === device &&
```
Comment (tomusborne) [inline src/extend/inspector-control/index.js:71]: This needs to be `Desktop` with a capital. It currently hides it on all devices.

File: src/extend/inspector-control/index.js [hunk 2]
```diff
@@ -68,14 +68,14 @@ export default function GenerateBlocksInspectorControls( { attributes, setAttrib
...
 				<ColorsControls
 					attributes={ attributes }
 					setAttributes={ setAttributes }
 				/>
 			}
 
-			{ backgroundPanel.enabled &&
+			{ backgroundPanel.enabled && 'desktop' === device &&
```
Comment (tomusborne) [inline src/extend/inspector-control/index.js:78]: Same as above.

**Comment by JeanPaiva** [comment]
Fixed.

**Review by tomusborne — APPROVED** [review]
