### PR TITLE
Fix: Add pointer-events to pseudo background

### LINKED ISSUE #859: Pseudo Backgrounds add `pointer-events: none`
### Description
Add `pointer-events: none` to pseudo backgrounds to allow click through when used as overlay

### Steps for testing
1.

#### References:
...

-----

### PR DESCRIPTION
**Pull request by JeanPaiva**
Closes #859

### CODE REVIEW

File: src/blocks/container/css/main.js [hunk 1]
```diff
@@ -198,6 +198,7 @@ export default function MainCSS( props ) {
 			'bottom': '0', // eslint-disable-line quote-props
 			'left': '0', // eslint-disable-line quote-props
 			'border-radius': shorthandCSS( borderRadiusTopLeft, borderRadiusTopRight, borderRadiusBottomRight, borderRadiusBottomLeft, borderRadiusUnit ),
+			'pointer-events': 'none',
```
Comment (tomusborne) [inline src/blocks/container/css/main.js:201]: We'll need to add this to the frontend CSS as well.

Comment (JeanPaiva) [reply src/blocks/container/css/main.js:201]: @tomusborne done.

**Review by tomusborne — APPROVED** [review]
