### PR TITLE
Fix dynamic bg images

### LINKED ISSUE #1357: GB 2.0 Pre-alpha - Container Dynamic Background does not render in the editor
### Description
Adding a dynamic data tag to the background of a container block does not render in the editor.

### PR DESCRIPTION
**Pull request by iansvo**
closes #1357

### CODE REVIEW

File: src/hoc/withHtmlAttributes.js [hunk 1]
```diff
@@ -68,16 +69,46 @@ export function withHtmlAttributes( WrappedComponent ) {
...
 		const { style = '', href, ...otherAttributes } = htmlAttributes;
-		const inlineStyleObject = typeof style === 'string'
-			? convertInlineStyleStringToObject( style )
-			: style;
+
+		useEffect( () => {
+			async function getReplacements() {
+			// Check if any replacements need to be made if not, do nothing.
+				if ( ! style.includes( '{{' ) ) {
+					return style;
```
Comment (tomusborne) [inline src/hoc/withHtmlAttributes.js:79]: @iansvo If we return early and never `setWithReplacements`, then the `inlineStyleObject` below would never have anything in it, right? I think we need some extra logic down there to see if `withReplacements` has a value.

Comment (iansvo) [reply src/hoc/withHtmlAttributes.js]: This is now updated

**Review by tomusborne — APPROVED** [review]
